"""Generate Dart lookups from the checked-in Spanish catalogues (stdlib only).

Run from the repository root: python tool/generate_spanish.py
The legacy S API is kept intact, including its positional argument order.
"""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parents[1]
base = json.loads((root / 'lib/l10n/intl_en.arb').read_text(encoding='utf-8'))
spanish = json.loads((root / 'lib/l10n/intl_es.arb').read_text(encoding='utf-8'))
legacy = (root / 'lib/generated/l10n.dart').read_text(encoding='utf-8')

def dart(value):
    return json.dumps(value, ensure_ascii=False).replace('$', '\\$')

messages = []
for key, source in base.items():
    if key.startswith('@'):
        continue
    translated = spanish[key]
    placeholders = re.findall(r'\{(\w+)\}', source)
    assert sorted(placeholders) == sorted(re.findall(r'\{(\w+)\}', translated)), key
    if placeholders:
        signature = re.search(r'String ' + key + r'\(([^)]*)\)', legacy)[1]
        args = [part.strip().split()[-1] for part in signature.split(',') if part.strip()]
        value = dart(translated)
        for arg in args:
            value = value.replace('{' + arg + '}', '${' + arg + '}')
        function = '(' + ', '.join(args) + ') => ' + value
    else:
        function = 'MessageLookupByLibrary.simpleMessage(' + dart(translated) + ')'
    messages.append('    ' + dart(key) + ': ' + function + ',')

(root / 'lib/generated/intl/messages_es.dart').write_text('''// Generated by tool/generate_spanish.py. Edit lib/l10n/intl_es.arb.
// ignore_for_file: unnecessary_brace_in_string_interps
import 'package:intl/message_lookup_by_library.dart';
final messages = MessageLookup();
class MessageLookup extends MessageLookupByLibrary {
  @override
  String get localeName => 'es';
  @override
  final Map<String, Function> messages = {
''' + '\n'.join(messages) + '\n  };\n}\n', encoding='utf-8')

extra = json.loads((root / 'lib/l10n/pregnancy_es.json').read_text(encoding='utf-8'))
for key, value in extra.items():
    assert sorted(re.findall(r'\{\d+\}', key)) == sorted(re.findall(r'\{\d+\}', value)), key
for key, value in base.items():
    if not key.startswith('@') and '{' not in value:
        extra.setdefault(value, spanish[key])
entries = '\n'.join('  ' + dart(k) + ': ' + dart(v) + ',' for k,v in extra.items())
(root / 'lib/generated/app_spanish.dart').write_text(
    '// Generated by tool/generate_spanish.py. Edit lib/l10n/pregnancy_es.json.\n'
    'const appSpanish = <String, String>{\n' + entries + '\n};\n', encoding='utf-8')
